In [4]:
!wget -nc -O downloads/es_2014.zip "http://www.fega.es/sites/default/files/files/Beneficiaries_municipality_financial_year_2014.txt"

--2017-05-18 14:14:03--  http://www.fega.es/sites/default/files/files/Beneficiaries_municipality_financial_year_2014.txt
Resolving www.fega.es... 93.188.52.193
Connecting to www.fega.es|93.188.52.193|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 121303371 (116M) [text/plain]
Saving to: ‘downloads/es_2014.zip’

downloads/es_2014.z 100%[===================>] 115.68M  1.08MB/s    in 92s

2017-05-18 14:15:35 (1.26 MB/s) - ‘downloads/es_2014.zip’ saved [121303371/121303371]

In [4]:
!wget -O downloads/es_2015.zip -nc "https://www.fega.es/sites/default/files/files/Beneficiaries_agricultural_district_financial_year_2015.zip"

--2017-05-17 20:51:14--  https://www.fega.es/sites/default/files/files/Beneficiaries_agricultural_district_financial_year_2015.zip
Resolving www.fega.es... 93.188.52.193
Connecting to www.fega.es|93.188.52.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19994764 (19M) [application/zip]
Saving to: ‘downloads/es_2015.zip’

downloads/es_2015.z 100%[===================>]  19.07M   363KB/s    in 59s

2017-05-17 20:52:13 (332 KB/s) - ‘downloads/es_2015.zip’ saved [19994764/19994764]

In [5]:
!wget -O downloads/es_2015_muni.zip -nc "https://www.fega.es/sites/default/files/files/Beneficiaries_municipality_financial_ year_2015.zip"

--2017-05-17 20:52:13--  https://www.fega.es/sites/default/files/files/Beneficiaries_municipality_financial_%20year_2015.zip
Resolving www.fega.es... 93.188.52.193
Connecting to www.fega.es|93.188.52.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22769302 (22M) [application/zip]
Saving to: ‘downloads/es_2015_muni.zip’

downloads/es_2015_m 100%[===================>]  21.71M   322KB/s    in 66s

2017-05-17 20:53:19 (337 KB/s) - ‘downloads/es_2015_muni.zip’ saved [22769302/22769302]

In [4]:
!wget -O downloads/es_2016.zip -nc "https://www.fega.es/sites/default/files/files/Beneficiaries_agricultural_district_financial_year_2016.zip"

--2018-02-05 11:48:58--  https://www.fega.es/sites/default/files/files/Beneficiaries_agricultural_district_financial_year_2016.zip
Resolving www.fega.es... 93.188.52.193
Connecting to www.fega.es|93.188.52.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23900577 (23M) [application/zip]
Saving to: ‘downloads/es_2016.zip’

downloads/es_2016.z 100%[===================>]  22.79M   233KB/s    in 96s

2018-02-05 11:50:34 (244 KB/s) - ‘downloads/es_2016.zip’ saved [23900577/23900577]

In [19]:
!wget -O downloads/es_2016_muni.zip -nc "https://www.fega.es/sites/default/files/files/Beneficiaries_municipality_financial_year_2016.zip"

--2018-02-05 12:02:00--  https://www.fega.es/sites/default/files/files/Beneficiaries_municipality_financial_year_2016.zip
Resolving www.fega.es... 93.188.52.193
Connecting to www.fega.es|93.188.52.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26194604 (25M) [application/zip]
Saving to: ‘downloads/es_2016_muni.zip’

downloads/es_2016_m 100%[===================>]  24.98M  98.0KB/s    in 2m 16s

2018-02-05 12:04:17 (188 KB/s) - ‘downloads/es_2016_muni.zip’ saved [26194604/26194604]

In [1]:
import pandas as pd

In [2]:
YEAR = 2016

In [12]:
df = pd.read_csv(f'downloads/es_{YEAR}.zip', delimiter=';', encoding='latin1', compression='zip')
df['year'] = YEAR
df = df.rename(columns={'COMARCA': 'MUNICIPIO'})
df.head()

,BENEFICIARIO,PROVINCIA,MUNICIPIO,MEDIDA,IMPORTE_EUROS,year
0,'A BOUCIÑA S.C.','A Coruña','1502 - OCCIDENTAL','II.1 Basic payment scheme ',"10666,27",2016
1,'A BOUCIÑA S.C.','A Coruña','1502 - OCCIDENTAL','II.7 Voluntary coupled support ',"9798,35",2016
2,'A BOUCIÑA S.C.','A Coruña','1502 - OCCIDENTAL','II.4 Payment for agricultural practices ben...,"390,02",2016
3,'A BOUCIÑA S.C.','A Coruña','1502 - OCCIDENTAL','II.10 Reimbursement of appropriations carri...,"248,57",2016
4,'A BOUCIÑA S.C.','A Coruña','1502 - OCCIDENTAL','III.11 Exceptional measures - Measures agai...,"3259,16",2016

In [14]:
cols = 'BENEFICIARIO	PROVINCIA	MUNICIPIO	MEDIDA'.split()
for c in cols:
    df[c] = df[c].str.replace(r"^'(.*)'$", '\\1')
df.head()

,BENEFICIARIO,PROVINCIA,MUNICIPIO,MEDIDA,IMPORTE_EUROS,year
0,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.1 Basic payment scheme,"10666,27",2016
1,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.7 Voluntary coupled support,"9798,35",2016
2,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.4 Payment for agricultural practices bene...,"390,02",2016
3,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.10 Reimbursement of appropriations carrie...,"248,57",2016
4,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,III.11 Exceptional measures - Measures again...,"3259,16",2016

In [20]:
df_muni = pd.read_csv(f'downloads/es_{YEAR}_muni.zip', delimiter=';', encoding='latin1', compression='zip')
df_muni['year'] = YEAR
df_muni = df_muni.rename(columns={'COMARCA': 'MUNICIPIO'})
df_muni.head()

,BENEFICIARIO,PROVINCIA,MUNICIPIO,MEDIDA,IMPORTE_EUROS,year
0,'A BOUCIÑA S.C.','A Coruña','15074 - Rois','II.1 Basic payment scheme ',"10666,27",2016
1,'A BOUCIÑA S.C.','A Coruña','15074 - Rois','II.7 Voluntary coupled support ',"9798,35",2016
2,'A BOUCIÑA S.C.','A Coruña','15074 - Rois','II.4 Payment for agricultural practices ben...,"390,02",2016
3,'A BOUCIÑA S.C.','A Coruña','15074 - Rois','II.10 Reimbursement of appropriations carri...,"248,57",2016
4,'A BOUCIÑA S.C.','A Coruña','15074 - Rois','III.11 Exceptional measures - Measures agai...,"3259,16",2016

In [21]:
cols = 'BENEFICIARIO	PROVINCIA	MUNICIPIO	MEDIDA'.split()
for c in cols:
    df[c] = df[c].str.replace(r"^'(.*)'$", '\\1')
df.head()

,BENEFICIARIO,PROVINCIA,MUNICIPIO,MEDIDA,IMPORTE_EUROS,year
0,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.1 Basic payment scheme,"10666,27",2016
1,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.7 Voluntary coupled support,"9798,35",2016
2,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.4 Payment for agricultural practices bene...,"390,02",2016
3,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.10 Reimbursement of appropriations carrie...,"248,57",2016
4,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,III.11 Exceptional measures - Measures again...,"3259,16",2016

In [22]:
len(df), len(df_muni)

(2019742, 2017686)

In [23]:
df = pd.concat([df, df_muni])

In [24]:
df['amount'] = pd.to_numeric(df['IMPORTE_EUROS'].str.replace(',', '.'))

In [25]:
df['recipient_postcode'] = df['MUNICIPIO'].str.split(' - ').apply(lambda x: x[0])
df.head()

,BENEFICIARIO,PROVINCIA,MUNICIPIO,MEDIDA,IMPORTE_EUROS,year,amount,recipient_postcode
0,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.1 Basic payment scheme,"10666,27",2016,10666.27,1502
1,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.7 Voluntary coupled support,"9798,35",2016,9798.35,1502
2,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.4 Payment for agricultural practices bene...,"390,02",2016,390.02,1502
3,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.10 Reimbursement of appropriations carrie...,"248,57",2016,248.57,1502
4,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,III.11 Exceptional measures - Measures again...,"3259,16",2016,3259.16,1502

In [26]:
df['recipient_location'] = df.apply(lambda x: '%s, %s' % (x['MUNICIPIO'].split(' - ')[1], x['PROVINCIA']), 1)
df.head()

,BENEFICIARIO,PROVINCIA,MUNICIPIO,MEDIDA,IMPORTE_EUROS,year,amount,recipient_postcode,recipient_location
0,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.1 Basic payment scheme,"10666,27",2016,10666.27,1502,"OCCIDENTAL, A Coruña"
1,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.7 Voluntary coupled support,"9798,35",2016,9798.35,1502,"OCCIDENTAL, A Coruña"
2,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.4 Payment for agricultural practices bene...,"390,02",2016,390.02,1502,"OCCIDENTAL, A Coruña"
3,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,II.10 Reimbursement of appropriations carrie...,"248,57",2016,248.57,1502,"OCCIDENTAL, A Coruña"
4,A BOUCIÑA S.C.,A Coruña,1502 - OCCIDENTAL,III.11 Exceptional measures - Measures again...,"3259,16",2016,3259.16,1502,"OCCIDENTAL, A Coruña"

In [27]:
from slugify import slugify

df = df.rename(columns={
    'BENEFICIARIO': 'recipient_name',
    'MEDIDA': 'scheme',
})
df = df.drop(['PROVINCIA', 'MUNICIPIO', 'IMPORTE_EUROS'], 1)
df['country'] = 'ES'
df['currency'] = 'EUR'
df['recipient_id'] = df.apply(lambda x: 'ES-%s-%s' % (x['recipient_postcode'], slugify(x['recipient_name'])), 1)
df.head()

,recipient_name,scheme,year,amount,recipient_postcode,recipient_location,country,currency,recipient_id
0,A BOUCIÑA S.C.,II.1 Basic payment scheme,2016,10666.27,1502,"OCCIDENTAL, A Coruña",ES,EUR,ES-1502-a-boucina-s-c
1,A BOUCIÑA S.C.,II.7 Voluntary coupled support,2016,9798.35,1502,"OCCIDENTAL, A Coruña",ES,EUR,ES-1502-a-boucina-s-c
2,A BOUCIÑA S.C.,II.4 Payment for agricultural practices bene...,2016,390.02,1502,"OCCIDENTAL, A Coruña",ES,EUR,ES-1502-a-boucina-s-c
3,A BOUCIÑA S.C.,II.10 Reimbursement of appropriations carrie...,2016,248.57,1502,"OCCIDENTAL, A Coruña",ES,EUR,ES-1502-a-boucina-s-c
4,A BOUCIÑA S.C.,III.11 Exceptional measures - Measures again...,2016,3259.16,1502,"OCCIDENTAL, A Coruña",ES,EUR,ES-1502-a-boucina-s-c

In [28]:
df.to_csv('es_2016.csv.gz', index=False, encoding='utf-8', compression='gzip')